spring.application.name=Md3-thi

spring.datasource.url=jdbc:postgresql://localhost:5432/buildingdb
spring.datasource.username=postgres
spring.datasource.password=33333
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
